107 main dialog fragment lost state
DavayPosmotrim/dv-android pull request #114
Opened 2024-07-03 06:32 UTC by MIkhaaaaa

Добавил сохранение в shared prefs имени пользователя

2024-07-03 14:28 UTC, Eka666Sed commented
Привет! При именовании commit на проекте принят такой формат:
"номер ветки_название коммита"

2024-07-03 14:52 UTC, Eka666Sed commented
Привет! При именовании ветки на проекте принят такой формат:
"номер ветки_bug_название ветки ", если таска по багу, как у тебя.

2024-07-03 15:08 UTC, Eka666Sed commented
В этой таске нужно было сделать совсем другое: добавить методы onSaveInstanceState и onViewStateRestored в MainDialogFragment. Что-то вроде такого:

override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        outState.putString(KEY_TITLE, title)
        outState.putString(KEY_MESSAGE, message)
    }

    override fun onViewStateRestored(savedInstanceState: Bundle?) {
        super.onViewStateRestored(savedInstanceState)
        if (savedInstanceState != null) {
            title = savedInstanceState.getString(KEY_TITLE)
            message = savedInstanceState.getString(KEY_MESSAGE)
            initViews()
        }
    }
    
    + добавить константы в companion object:
    
    private const val KEY_TITLE = "KEY_TITLE"
    private const val KEY_MESSAGE = "KEY_MESSAGE"
    
    P.S.: возможно стоит уточнить у Дениса (он оставлял этот комментарий)

2024-07-06 13:09 UTC, Eka666Sed commented
Добавь себя в PR в разделе Assignees и в issue на эту задачу нужно добавить  PR в разделе Development.

2024-07-15 16:36 UTC, Eka666Sed commented on uikit/src/main/java/com/davai/uikit/MainDialogFragment.kt
> +    override fun onViewStateRestored(savedInstanceState: Bundle?) {
Здесь onSaveInstanceState должен вызывается первым (когда нужно сохранить текущее состояние). onViewStateRestored вызывается, чтобы восстановить это состояние.

2024-07-15 16:36 UTC, Eka666Sed approved these changes

2024-07-15 22:33 UTC, Secur1ty-21 requested changes
Все еще не сохраняет обработчики нажатий на кнопки диалога: думаю стоит вынести сохранение в viewModel
https://github.com/user-attachments/assets/5bac7a10-942e-44d3-9992-a681ebba2947

2024-07-21 10:26 UTC, Eka666Sed commented
Все еще не сохраняется обработчик нажатий.
viewModel не появилась.

2024-07-24 09:52 UTC, Secur1ty-21 requested changes

2024-07-24 09:52 UTC, Secur1ty-21 commented on uikit/src/main/java/com/davai/uikit/MainDialogFragment.kt
> +            viewModel.noAction = noAction
Нельзя создать viewModel пока фрагмент не присоединен к activity, при переходе на экран с диалогом выкидывает exception ->
java.lang.IllegalStateException: Fragment MainDialogFragment{af9122b} (49632b60-4f77-4d85-aca3-f7eeac8417a5) not attached to an activity.
                                                                                                    	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:1000)
                                                                                                    	at com.davai.uikit.MainDialogFragment$Companion.newInstance(MainDialogFragment.kt:106)


Необходимо  при создании диалога временно сохранить title, message, yesAction, noAction в поля класса. В onViewCreated инициализировать viewModel и сохранить эти поля туда. Далее использовать поля именно из viewModel.

2024-07-30 14:42 UTC, Eka666Sed commented on uikit/src/main/java/com/davai/uikit/MainDialogFragment.kt
> +        if (yesAction != null) {
Можно сделать так:
 viewModel.yesAction = yesAction ?: viewModel.yesAction
 viewModel.noAction = noAction ?: viewModel.noAction

2024-07-30 14:52 UTC, Eka666Sed approved these changes

2024-07-30 17:52 UTC, MIkhaaaaa commented on uikit/src/main/java/com/davai/uikit/MainDialogFragment.kt
> +        if (yesAction != null) {
Да, так действительно красивее)

2024-07-31 10:39 UTC, muskilon approved these changes

2024-08-03 23:03 UTC, Secur1ty-21 approved these changes

2024-08-03 23:04 UTC, merged