6-text-styles
DavayPosmotrim/dv-android pull request #21
Opened 2024-04-28 11:51 UTC by HatePK

Fonts and text styles added

2024-04-29 13:10 UTC, DimaK21 approved these changes

2024-04-29 19:15 UTC, GoetzDeBouville requested changes
Предлагаю переделать стили с учетом наследования/расширения и соглашения по нэймингу, примеры в статьях:
https://seanghay.medium.com/themes-styles-in-android-5a017430c09e
https://developer.android.com/develop/ui/views/theming/themes
И вот пример, как делал Николай:
<img width="550" alt="Снимок экрана 2024-04-29 в 22 13 56" src="https://github.com/DavayPosmotrim/dv-android/assets/31970713/271b8b50-af9c-4a25-a908-3b55a304be9b">

2024-04-30 20:38 UTC, HatePK commented
> Предлагаю переделать стили с учетом наследования/расширения и соглашения по нэймингу, примеры в статьях>

Переделал, спасибо

2024-05-01 07:42 UTC, GoetzDeBouville approved these changes
approve, если понадобится, будем корректировать

2024-05-02 06:37 UTC, n-shvedov27 approved these changes

2024-05-02 06:37 UTC, merged