10 create custom view movie evaluation
DavayPosmotrim/dv-android pull request #22
Opened 2024-05-02 20:23 UTC by GoetzDeBouville

Добавляет кастомную view оценки фильма
https://www.figma.com/file/18yNJmNYwWsexJku2SpWWE/%D0%94%D0%B0%D0%B2%D0%B0%D0%B9-%D0%BF%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B8%D0%BC?type=design&node-id=179-1825&mode=design&t=5JPjVoKX7QkDlr0c-4

2024-05-03 08:30 UTC, HatePK approved these changes

2024-05-06 07:37 UTC, DimaK21 approved these changes

2024-05-06 09:30 UTC, Megrief commented on uikit/src/main/java/com/davai/uikit/MovieEvaluationVIew.kt
> +    private fun applyAttributes(
А ты не смотрел вариант с extension функцией в примере? Мне кажется он более аккуратно смотрится.
`inline fun AttributeSet.applyStyleable(
    context: Context,
    @StyleableRes styleableResId: IntArray,
    action: TypedArray.() -> Unit
) {
    val typedArray = context.obtainStyledAttributes(this, styleableResId)
    typedArray.action()
    typedArray.recycle()
}`
И вот пример реализации:
`attrs?.applyStyleable(context, R.styleable.TabCustomView) {
            text.text = getString(R.styleable.TabCustomView_tabText)
            text.setTextColor(getColor(R.styleable.TabCustomView_tabTextColor, Color.BLACK))
        }`

2024-05-06 20:20 UTC, GoetzDeBouville commented on uikit/src/main/java/com/davai/uikit/MovieEvaluationVIew.kt
> +    private fun applyAttributes(
Можно конечно написать расширение для аплай, но по сути в нашей задаче кастомных атрибутов на самом деле и не требуется, так что пользоваться этим расширением никто не будет.
Плюс я не понял на что ссылается this в твоем примере

2024-05-07 05:54 UTC, n-shvedov27 requested changes

2024-05-07 05:54 UTC, n-shvedov27 commented on uikit/src/main/java/com/davai/uikit/MovieEvaluationVIew.kt
> +        val formattedNumber = String.format("%,d", numberOfRates).replace(",", " ")
`String.format(Locale.ROOT, ...`

И SuppressLint, и Suppress можно убрать

2024-05-07 05:54 UTC, n-shvedov27 commented on uikit/src/main/java/com/davai/uikit/MovieEvaluationVIew.kt
> +    @Suppress("Detekt.MagicNumber")
Кажется этот Suppress тоже больше не нужен

2024-05-07 07:31 UTC, GoetzDeBouville commented on uikit/src/main/java/com/davai/uikit/MovieEvaluationVIew.kt
> +        val formattedNumber = String.format("%,d", numberOfRates).replace(",", " ")
Пофиксил

2024-05-07 07:31 UTC, GoetzDeBouville commented on uikit/src/main/java/com/davai/uikit/MovieEvaluationVIew.kt
> +    @Suppress("Detekt.MagicNumber")
Пофиксил

2024-05-08 05:29 UTC, n-shvedov27 approved these changes

2024-05-08 12:40 UTC, merged