12 create custom view movie selection
DavayPosmotrim/dv-android pull request #23
Opened 2024-05-02 20:56 UTC by GoetzDeBouville

Добавляет кастомную view селектор подборки
https://www.figma.com/file/18yNJmNYwWsexJku2SpWWE/%D0%94%D0%B0%D0%B2%D0%B0%D0%B9-%D0%BF%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B8%D0%BC?type=design&node-id=156-2370&mode=design&t=5JPjVoKX7QkDlr0c-4

2024-05-03 05:29 UTC, n-shvedov27 commented
Направь плз этот ПР в ветку 10_create_custom_view_movie_evaluation, чтобы дифф более читаемый был
Когда 10_create_custom_view_movie_evaluation сольется направишь этот пр в develop

2024-05-03 06:31 UTC, GoetzDeBouville commented
> Направь плз этот ПР в ветку 10_create_custom_view_movie_evaluation, чтобы дифф более читаемый был Когда 10_create_custom_view_movie_evaluation сольется направишь этот пр в develop
получается нужно дождаться мёрджа 10 ветки и только потом 12?

2024-05-04 10:52 UTC, DimaK21 approved these changes

2024-05-04 10:52 UTC, DimaK21 commented on uikit/src/main/java/com/davai/uikit/MovieSelectionView.kt
> +                    radius = resources.getDimensionPixelSize(R.dimen.card_radius_16).toFloat()
Чтобы толщина зеленой/белой линии вокруг вьюхи была одного размера в углах, то внешний и внутренний радиус можно сделать отличными на величину ширины этой линии.
То есть можно или здесь радиус уменьшить на 8 (внутренний радиус), либо увеличить внешний радиус на 8.

Еще трансформация у coil работает только к основному изображению, то есть в плейсхолдерах, которые у нас потом будут, нужно чтобы углы уже были скруглены.

2024-05-04 10:52 UTC, DimaK21 commented on uikit/src/main/java/com/davai/uikit/MovieSelectionView.kt
> +package com.davai.uikit
к делу не относится конечно, но у нас пакеты опять по-разному называются))
в app com.davay

2024-05-04 11:13 UTC, Megrief approved these changes

2024-05-04 13:50 UTC, GoetzDeBouville commented on uikit/src/main/java/com/davai/uikit/MovieSelectionView.kt
> +                    radius = resources.getDimensionPixelSize(R.dimen.card_radius_16).toFloat()
Спасибо за замечания, тут нужно было не апрувить))
По поводу трансформации убил 2 часа времени чтобы заставить скруглить углы на плейсхолдере и на ошибках.

2024-05-04 13:51 UTC, GoetzDeBouville commented on uikit/src/main/java/com/davai/uikit/MovieSelectionView.kt
> +package com.davai.uikit
я снова накосячил, можем выделить один ПР на то, чтобы переименовать пакеты

2024-05-04 13:59 UTC, GoetzDeBouville commented on uikit/src/main/java/com/davai/uikit/MovieSelectionView.kt
> +                    radius = resources.getDimensionPixelSize(R.dimen.card_radius_16).toFloat()
<img width="746" alt="Снимок экрана 2024-05-04 в 16 59 20" src="https://github.com/DavayPosmotrim/dv-android/assets/31970713/a561f81b-ba2d-42bc-b43e-2127978ddf30">
Пофиксил радиус скругления

2024-05-06 07:53 UTC, n-shvedov27 commented on uikit/src/main/java/com/davai/uikit/MovieEvaluationVIew.kt
Почему этот файл в диффе?

2024-05-06 11:09 UTC, GoetzDeBouville commented
Пофиксил скругления углов для любых изображений (apceholder и error)
<img width="237" alt="Снимок экрана 2024-05-06 в 14 07 51" src="https://github.com/DavayPosmotrim/dv-android/assets/31970713/d513c46b-ab4f-4b41-8b99-14068e5228c3">

2024-05-07 05:59 UTC, n-shvedov27 approved these changes

2024-05-07 06:00 UTC, n-shvedov27 requested changes
Конфликты

2024-05-07 07:45 UTC, GoetzDeBouville commented
> Конфликты

Зарезолвил

2024-05-08 05:30 UTC, n-shvedov27 approved these changes

2024-05-08 05:31 UTC, n-shvedov27 reviewed
Поменять target-ветку на develop

2024-05-08 05:32 UTC, n-shvedov27 commented on uikit/src/main/java/com/davai/uikit/MovieSelectionView.kt
Поменять target-ветку на develop

2024-05-08 12:14 UTC, merged