13 view dv session
DavayPosmotrim/dv-android pull request #24
Opened 2024-05-04 19:21 UTC by HatePK

- базовая верстка
- атрибуты кастом класса
- класс SessionView
- добавление сампла

2024-05-05 08:25 UTC, GoetzDeBouville commented on uikit/src/main/java/com/davai/uikit/SessionView.kt
> +    private var body: LinearLayout? = null
body инициализируется, но нигде не используется, по макету его параметры тоже не требуется изменять, давай удалим его

2024-05-05 09:07 UTC, GoetzDeBouville requested changes
Оставил комменты, из критичного - большая вложенность в макете кастомной вью, этого следует избегать

2024-05-05 09:07 UTC, GoetzDeBouville commented on uikit/src/main/java/com/davai/uikit/SessionView.kt
> +    }
Тут компилятор должен был ругаться, т.к. session_coincidences принимает строку, а ты передаешь Int, кастони его в строку прямо тут

2024-05-05 09:07 UTC, GoetzDeBouville commented on uikit_sample/src/main/java/com/davai/uikit_sample/SessionExample.kt
> +    }
на мой взгляд, в семплах не обязательно "слушаться" detekt, а просто делать supress на его предупреждениях

2024-05-05 12:35 UTC, GoetzDeBouville approved these changes

2024-05-06 19:28 UTC, DimaK21 approved these changes

2024-05-07 06:00 UTC, n-shvedov27 approved these changes

2024-05-07 06:00 UTC, merged