5 view dvbutton
DavayPosmotrim/dv-android pull request #25
Opened 2024-05-05 20:23 UTC by DimaK21

два класса для кнопок: PrimaryButtonView, SecondaryButtonView

2024-05-06 20:42 UTC, GoetzDeBouville commented on uikit/src/main/java/com/davai/uikit/PrimaryButtonView.kt
> +        setLoading(buttonLoading)
кажется блок init большеват, но это вкусовщина

2024-05-06 20:55 UTC, GoetzDeBouville commented
С учетом того что 10 и 12 ветки не влиты, получается большой объем кода в ПР. Может сделать пр в 12 ветку в таком случае?
12 ветка обновилась, мерджни ее в 5 снова

2024-05-06 20:56 UTC, GoetzDeBouville approved these changes

2024-05-07 16:54 UTC, DimaK21 commented
> С учетом того что 10 и 12 ветки не влиты, получается большой объем кода в ПР. Может сделать пр в 12 ветку в таком случае? 12 ветка обновилась, мерджни ее в 5 снова

12 залил в 5

2024-05-07 16:55 UTC, DimaK21 commented on uikit/src/main/java/com/davai/uikit/PrimaryButtonView.kt
> +        setLoading(buttonLoading)
можно разбить, конечно
но мне кажется не такой уж большой

2024-05-10 18:06 UTC, NikolayRyabcev approved these changes

2024-05-13 06:38 UTC, n-shvedov27 requested changes

2024-05-13 06:38 UTC, n-shvedov27 commented on uikit/src/main/java/com/davai/uikit/PrimaryButtonView.kt
> +class PrimaryButtonView @JvmOverloads constructor(
Почему PrimaryButtonView и SecondaryButtonView не один компонент?

2024-05-13 13:15 UTC, DimaK21 commented on uikit/src/main/java/com/davai/uikit/PrimaryButtonView.kt
> +class PrimaryButtonView @JvmOverloads constructor(
переделал в один класс и один лэйаут

2024-05-14 06:59 UTC, n-shvedov27 approved these changes

2024-05-14 07:00 UTC, merged