14 create custom view film
DavayPosmotrim/dv-android pull request #26
Opened 2024-05-06 10:24 UTC by GoetzDeBouville

Создает кастомную вью карточки фильма https://www.figma.com/file/18yNJmNYwWsexJku2SpWWE/%D0%94%D0%B0%D0%B2%D0%B0%D0%B9-%D0%BF%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B8%D0%BC?type=design&node-id=171-10800&mode=design&t=G1afB0JOrPeKjl2k-4

2024-05-06 13:13 UTC, HatePK requested changes

2024-05-06 13:13 UTC, HatePK commented on uikit/src/main/res/layout/movie_card_view.xml
> +        android:layout_marginEnd="@dimen/margin_16"
горизонтальные марджины 20dp по макету

2024-05-06 13:49 UTC, GoetzDeBouville commented on uikit/src/main/res/layout/movie_card_view.xml
> +        android:layout_marginEnd="@dimen/margin_16"
Согласно конвенции Material Design размеры должны быть кратны 8, и только иногда 4, поэтому я часто игнорирую дизайнеров, т.к. они могут не знать конвенции. Статья тут:
https://m2.material.io/design/layout/understanding-layout.html#material-measurements

2024-05-06 13:52 UTC, HatePK approved these changes

2024-05-06 19:59 UTC, GoetzDeBouville commented on uikit/src/main/res/layout/movie_card_view.xml
> +        android:layout_marginEnd="@dimen/margin_16"
Установил отступы по горизонтали 20dp

2024-05-08 09:05 UTC, Megrief approved these changes

2024-05-13 06:37 UTC, n-shvedov27 approved these changes

2024-05-13 06:37 UTC, merged