28 layout onboarding screen
DavayPosmotrim/dv-android pull request #38
Opened 2024-05-13 11:41 UTC by GoetzDeBouville

Добавляет фрагмент экрана онбординга (верстка и навигация)
https://www.figma.com/design/18yNJmNYwWsexJku2SpWWE/%D0%94%D0%B0%D0%B2%D0%B0%D0%B9-%D0%BF%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B8%D0%BC?node-id=472-1665&t=sSWTdsNrlIcqgpui-4

2024-05-14 11:17 UTC, closed without merging

2024-05-18 18:03 UTC, Eka666Sed commented
Привет! Заметила мини ошибку на кнопке "Продолжить" (лишняя буква "л").
![Uploading mistake_orfo.jpg…]()

2024-05-18 18:18 UTC, Eka666Sed commented
![quality_picture](https://github.com/DavayPosmotrim/dv-android/assets/130983590/966d97ff-5e8f-41aa-9514-162a6c3adadc)
Есть ли возможность сделать качество картинки выше на fragment_onboarding_third? Мое субъективное мнение: сейчас текст как бы расплывается.

2024-05-18 18:32 UTC, Eka666Sed commented
Возможно для картинок стоит добавить стиль, чтобы убрать повторяющийся код.

2024-05-18 21:34 UTC, GoetzDeBouville commented
> Возможно для картинок стоит добавить стиль, чтобы убрать повторяющийся код.
> 
> P.S.: код посмотрела, комментарии оставила. Апрув поставить не могу, т.к. не прицеплена.

этот пр висит уже неделю, так что считаем что он хвост тех кто обозначен ревьюером, а не новеньких ))

2024-05-18 21:35 UTC, GoetzDeBouville commented
> ![quality_picture](https://private-user-images.githubusercontent.com/130983590/331821754-966d97ff-5e8f-41aa-9514-162a6c3adadc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNjgxMDcsIm5iZiI6MTcxNjA2NzgwNywicGF0aCI6Ii8xMzA5ODM1OTAvMzMxODIxNzU0LTk2NmQ5N2ZmLTVlOGYtNDFhYS05NTE0LTE2MmE2YzNhZGFkYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQyMTMwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTNlZGFmNDE2ZTk5NGIyZmJhZTI3NmMwNTkwOTFlMTgxNjdlYWU4YTI0YjdjZmQyMDhlZTA4NDhmZWQyYzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5RGz3HWyl9TEkLutcZRoeHrp3YPUJdHWkgophqE55bU) Есть ли возможность сделать качество картинки выше на fragment_onboarding_third? Мое субъективное мнение: сейчас текст как бы расплывается.

вот этот вопрос наверное вынесем на обсуждение, т.к. лучше все-таки собрать эту картинку, чем тащить png или огромный svg

2024-05-19 17:31 UTC, HatePK approved these changes

2024-05-20 05:16 UTC, n-shvedov27 commented on app/src/main/res/layout/fragment_onboarding.xml
> +    <me.relex.circleindicator.CircleIndicator3
Что это за вьюха?

2024-05-20 05:16 UTC, n-shvedov27 commented on conf/custom-detekt.yml
> +        threshold: 40
Зачем это менять?

2024-05-20 05:17 UTC, n-shvedov27 requested changes

2024-05-20 05:17 UTC, n-shvedov27 commented on app/src/main/res/drawable/img_favorite_film.webp
Эти картинки надо скачать в svg формате и в андроид студии перевести в xml-drawable

2024-05-20 09:57 UTC, GoetzDeBouville commented on conf/custom-detekt.yml
> +        threshold: 40
Вернул в стандартные, там почему-то была длина 60

2024-05-20 09:58 UTC, GoetzDeBouville commented on app/src/main/res/drawable/img_favorite_film.webp
в svg получается объём 500+ кБ

2024-05-20 10:00 UTC, DimaK21 commented on app/src/main/res/drawable/img_favorite_film.webp
А после перевода в xml?

2024-05-20 10:07 UTC, GoetzDeBouville commented on app/src/main/res/drawable/img_favorite_film.webp
> А после перевода в xml?

сейчас гляну

2024-05-20 10:19 UTC, GoetzDeBouville commented on app/src/main/res/drawable/img_favorite_film.webp
> А после перевода в xml?
Ошибки при декодировании любой картинки, к тому же я сомневаюсь что объем файла сильно изменится
<img width="406" alt="Снимок экрана 2024-05-20 в 13 18 27" src="https://github.com/DavayPosmotrim/dv-android/assets/31970713/b4d769f5-0206-4d4a-a604-19cb50382fa9">

2024-05-20 10:23 UTC, GoetzDeBouville commented on app/src/main/res/drawable/img_favorite_film.webp
И обнаружил, что я добавил не оригинальные картинки, в оригинальном размере самый большой webp получается 603 кБ 🫢

2024-06-03 06:46 UTC, n-shvedov27 approved these changes