32 layout registration screen
DavayPosmotrim/dv-android pull request #45
Opened 2024-05-14 15:27 UTC by DimaK21

Экран регистрации

2024-05-16 15:11 UTC, DimaK21 commented
Чтобы проверить, как работает невозможность скрыть клавиатуру (это новое требование заказчика), необходимо в LoadFragment вместо 
`viewModel.navigate(R.id.action_loadFragment_to_registrationFragment) `
написать 
`findNavController().navigate(R.id.action_loadFragment_to_registrationFragment)`
так как сейчас навигация назад через viewModel не работает

2024-05-16 23:39 UTC, GoetzDeBouville commented
> Чтобы проверить, как работает невозможность скрыть клавиатуру (это новое требование заказчика), необходимо в LoadFragment вместо `viewModel.navigate(R.id.action_loadFragment_to_registrationFragment) ` написать `findNavController().navigate(R.id.action_loadFragment_to_registrationFragment)` так как сейчас навигация назад через viewModel не работает

2024-05-16 23:46 UTC, GoetzDeBouville commented on app/src/main/java/com/davay/android/app/MainActivity.kt
> +        }
нельзя сделать эту настройку в манифесте?

2024-05-17 07:22 UTC, DimaK21 commented on app/src/main/java/com/davay/android/app/MainActivity.kt
> +        }
Насколько я понял, нельзя

2024-05-17 08:30 UTC, GoetzDeBouville approved these changes
Оставил комменты

2024-05-17 08:30 UTC, GoetzDeBouville commented on app/src/main/res/values/dimens.xml
> +<resources>
я запутался, где у нас должны были быть dimens только в uikit или в app свой? ))) я все кидаю в uikit

2024-05-17 09:31 UTC, DimaK21 commented on app/src/main/res/values/strings.xml
> +    <string name="enter">Войти</string>
переименовал

2024-05-17 09:32 UTC, DimaK21 commented on app/src/main/java/com/davay/android/feature/registration/presentation/RegistrationFragment.kt
> +            // что-то делаем
да, сделал на мэйн переход

2024-05-17 09:32 UTC, DimaK21 commented on app/src/main/java/com/davay/android/feature/registration/presentation/RegistrationViewModel.kt
> +            _state.value = RegistrationState.FIELD_EMPTY
переделал

2024-05-17 09:32 UTC, DimaK21 commented on app/src/main/res/values/dimens.xml
> +<resources>
перенес в uikit и переименовал

2024-05-17 14:19 UTC, Megrief approved these changes

2024-05-20 05:21 UTC, n-shvedov27 requested changes

2024-05-20 05:21 UTC, n-shvedov27 commented on uikit/src/main/java/com/davai/uikit/ImeBackEditText.kt
> +    constructor(context: Context, attrs: AttributeSet?, defStyleAttr: Int) : super(
Можно добавить один конструктор с аннотацией @JvmOverloads

2024-05-20 05:21 UTC, n-shvedov27 commented on uikit/src/main/java/com/davai/uikit/ImeBackEditText.kt
> +class ImeBackEditText : AppCompatEditText {
Что значит 'Ime" ?

2024-05-20 05:23 UTC, n-shvedov27 requested changes

2024-05-20 05:23 UTC, n-shvedov27 commented on uikit/src/main/res/values/styles.xml
> +        <item name="android:textColor">@color/text_base</item>
Тут точно нужны новые стили?

2024-05-21 21:45 UTC, DimaK21 commented
@Megrief Так как решили автоматический отступ сверху убрать, я здесь добавил отступ сверху для логотипа на главном экране на величину статус бара. И фон на главном получается белое на белом, а в фигме белое на сером. Поэтому поставил, чтоб серый цвет был.

2024-05-21 21:48 UTC, DimaK21 commented on uikit/src/main/java/com/davai/uikit/ImeBackEditText.kt
> +class ImeBackEditText : AppCompatEditText {
переименовал в KeyboardBackEditText

2024-05-21 21:48 UTC, DimaK21 commented on uikit/src/main/res/values/styles.xml
> +        <item name="android:textColor">@color/text_base</item>
сделал без стилей

2024-05-22 05:55 UTC, n-shvedov27 approved these changes

2024-05-22 05:55 UTC, merged