9 view dvbanner
DavayPosmotrim/dv-android pull request #47
Opened 2024-05-16 05:09 UTC by Megrief

Добавлена custom view DvBanner

2024-05-16 10:13 UTC, GoetzDeBouville requested changes
Оставил комменты, из критичного - не кастомизируется цвет фона, скриншот в комменте

2024-05-19 20:21 UTC, DimaK21 approved these changes
Оказывается у нас эти баннеры готовые есть, а я верстал сидел

2024-05-19 20:37 UTC, DimaK21 requested changes
Мне нужен баннер, но с другим текстом. А метод setBannerText приватный

2024-05-19 22:10 UTC, HatePK approved these changes

2024-05-19 22:10 UTC, HatePK commented on uikit/src/main/java/com/davai/uikit/BannerView.kt
> +    private fun setBannerText(value: String) {
Мне кажется, что этот метод должен быть публичным, и тексты ошибок не захардкожены в State. Вдруг потом будет использоваться в нескольких местах.

2024-05-19 22:12 UTC, HatePK commented on uikit/src/main/java/com/davai/uikit/BannerView.kt
> +    private fun setBannerText(value: String) {
Ой, Дима уже написал выше. Сорри.

2024-05-20 05:27 UTC, n-shvedov27 approved these changes

2024-05-20 05:52 UTC, Megrief commented on uikit/src/main/java/com/davai/uikit/BannerView.kt
> +    private fun setBannerText(value: String) {
@DimaK21 @HatePK готово.

2024-05-20 07:31 UTC, DimaK21 approved these changes

2024-05-20 10:00 UTC, merged