60 coincidences screen
DavayPosmotrim/dv-android pull request #88
Opened 2024-06-08 10:15 UTC by Megrief

Завершена верстка экрана CoincidencesFragment. 
Добавлены классы для тестирования: TestMovie, TestMovieRepository.

2024-06-08 21:36 UTC, GoetzDeBouville approved these changes
Оставил несколько комментов, но предлагаю сразу уже сделать экран с инфо о фильме и при переходе на него сразу передавать экземпляр фильма (коммент про это тоже оставил)

2024-06-08 21:36 UTC, GoetzDeBouville commented on app/src/main/java/com/davay/android/utils/CheckNetworkState.kt
> +fun checkNetworkState(connectivityManager: ConnectivityManager?): Boolean {
Думаю, что логичнее сделать его через расширение контекста, на котором мы получаем ConnectivityManager

```kotlin
fun Context.checkInternetReachability(): Boolean {
    val connectivityManager = this.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
    val activeNetwork =
        connectivityManager.activeNetwork?.let { connectivityManager.getNetworkCapabilities(it) } ?: return false
    return when {
        activeNetwork.hasTransport(NetworkCapabilities.TRANSPORT_WIFI) -> true
        activeNetwork.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR) -> true
        else -> false
    }
}
```

2024-06-08 21:36 UTC, GoetzDeBouville commented on app/src/main/java/com/davay/android/utils/CheckNetworkState.kt
> +fun checkNetworkState(connectivityManager: ConnectivityManager?): Boolean {
Еще есть вариант через BroadcastReciever обновлять статус сети как в плейлистмэйкере или через объект NetworkCallback(), но я хз как конкретно в нашем проекте лучше

2024-06-08 21:36 UTC, GoetzDeBouville commented on app/src/main/java/com/davay/android/feature/coincidences/presentation/CoincidencesFragment.kt
> +//        error: Boolean = false,
Почему ошибка закомментирована? У нас нет дизайна под ошибку?

2024-06-08 21:36 UTC, GoetzDeBouville commented on app/src/main/java/com/davay/android/feature/coincidences/presentation/adapter/MoviesGridDecoration.kt
> +        val marginInPx8 = view.resources.getDimensionPixelSize(com.davai.uikit.R.dimen.margin_8)
уже оставлял коммент похожий, что лучше создать отдельный item_layout со всеми отступами вместо того, чтобы использовать view и вешать доп отступы, обычно ведь ItemDecoration используется для того, чтобы определить какие-то кастомные отступы, которые нельзя определить в верстке заранее

2024-06-08 21:36 UTC, GoetzDeBouville commented on app/src/main/res/layout/fragment_coincidences.xml
> +        <ProgressBar
Что-то я не увидел варианта дизайна с прогресс баром

2024-06-08 21:36 UTC, GoetzDeBouville commented on app/src/main/res/layout/fragment_coincidences.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
забыл отформатировать Ctrl+Alt+L/option+cmd+L

2024-06-08 21:36 UTC, GoetzDeBouville commented on app/src/main/res/values/strings.xml
> +    <string name="coincidences">Совпадения</string>
именя строковым ресурсам мы даем по правилу имя_экрана_имя_ресурса (coincidences_empty_coincidences)

2024-06-08 21:36 UTC, GoetzDeBouville commented on app/src/main/res/values/strings.xml
> +    <string name="url1">https://images.squarespace-cdn.com/content/v1/57488e28746fb940f103c64e/1626726014496-MF7OB9OBHLB21UR0LJV0/Fellowship+for+Trailer.jpg</string>
Лучше все-таки вынести моковые данные из ресурсов и положить списком готовых экземпляров прямо в репозиторий, т.к. ты от него провайдишь данные. я сам не стал заморачиваться и положил прямо в [файл фрагмента ](https://github.com/DavayPosmotrim/dv-android/blob/86dacd8a81098f1b930bab13fc997a77bc6d8ed1/app/src/main/java/com/davay/android/feature/selectmovie/presentation/SelectMovieFragment.kt#L183), на этапе верстки это не критично, но ресурсы это то что уходит в прод по идее

2024-06-08 21:36 UTC, GoetzDeBouville commented on uikit/src/main/res/drawable/ic_random.xml
> +      android:fillColor="#3A3A3A"
Цвета устанавливаем из ресурсов

2024-06-08 21:36 UTC, GoetzDeBouville commented on uikit/src/main/res/drawable/ic_random.xml
> +      android:fillColor="#3A3A3A"
тут тоже цвет ставим из ресурсов

2024-06-08 21:36 UTC, GoetzDeBouville commented on uikit/src/main/res/drawable/placeholder_empty.xml
> +    <path android:fillColor="#DDDDDD" android:fillType="evenOdd" android:pathData="M44.31,171.75C37.54,171.75 31.98,169.13 28.49,164.52C26.72,162.18 25.6,159.49 25.15,156.57L25.14,156.51L2.8,54.1C1.7
цвет из ресуров

2024-06-09 02:12 UTC, Megrief commented on app/src/main/java/com/davay/android/feature/coincidences/presentation/CoincidencesFragment.kt
> +    ) {
В принципе, можно. Но тогда придется переименовывать аргументы функции. Либо дописывать this вместо binding.

2024-06-09 02:18 UTC, Megrief commented on app/src/main/java/com/davay/android/feature/coincidences/presentation/CoincidencesFragment.kt
> +//        error: Boolean = false,
Готового нет, поэтому закомментировал.

2024-06-09 09:29 UTC, GoetzDeBouville commented on app/src/main/java/com/davay/android/feature/coincidences/presentation/CoincidencesFragment.kt
> +    ) {
ну если переименовать аргументы, то this не понадобится

2024-06-09 09:32 UTC, GoetzDeBouville commented on app/src/main/java/com/davay/android/feature/coincidences/presentation/CoincidencesFragment.kt
> +    ) {
```kotlin
    private fun hideExclude(
        progressBarIsVisible: Boolean = false,
        coincidencesListIsVisible: Boolean = false,
        emptyMessageIsVisible: Boolean = false
    ) = with(binding){
        progressBar.isVisible = progressBarIsVisible
        coincidencesList.isVisible = coincidencesListIsVisible
        emptyPlaceholder.root.isVisible = emptyMessageIsVisible
    }
```

2024-06-09 10:45 UTC, DimaK21 commented
https://github.com/DavayPosmotrim/dv-android/assets/95705584/48ba2568-efda-4f2d-a1f4-36bc48cb9919


странно плейсхолдеры меняют масштабирование, при появлении (сверху экрана на видео)

Еще на этом экране должна быть кнопка перехода на рулетку и боттом шит, который срабатывает один раз.

2024-06-09 10:48 UTC, GoetzDeBouville commented
> странно плейсхолдеры меняют масштабирование, при появлении (сверху экрана на видео)
> 
> Еще на этом экране должна быть кнопка перехода на рулетку и боттом шит, который срабатывает один раз.

мы как раз это обсуждали с Женей, все потому что плейсхолдеры сами по себе разные, предлагаю забить на то что дает заказчик и заменить плейсхолдер процесса загрузки на плейсхолдер ошибки, но без текста

2024-06-10 13:16 UTC, Megrief commented on app/src/main/java/com/davay/android/feature/coincidences/presentation/CoincidencesFragment.kt
> +    ) {
Но и код не сокращается)

2024-06-12 10:14 UTC, DimaK21 commented on uikit/build.gradle.kts
> +        viewBinding = true
этот блок уже есть чуть ниже

2024-06-12 12:07 UTC, Secur1ty-21 requested changes
Заметил что не учел что название фильма может быть длинным + на белом фоне белый текст не видно, сформируй вопрос заказчику что делать при белой обложке фильма

<img width="328" alt="image" src="https://github.com/DavayPosmotrim/dv-android/assets/72816249/725e2851-3b47-4669-88e2-bafac9aef3bf">

2024-06-12 12:07 UTC, Secur1ty-21 commented on app/src/main/java/com/davay/android/feature/coincidences/presentation/CoincidencesFragment.kt
> +//                            }
Хорошо бы добавить тост на данном этапе и подчистить закомментированный код

2024-06-12 12:07 UTC, Secur1ty-21 commented on app/src/main/java/com/davay/android/feature/coincidences/presentation/adapter/MoviesGridAdapter.kt
> +        }
Лучше вынести установку clickListener в onCreateViewHolder

2024-06-12 14:17 UTC, Megrief commented on app/src/main/java/com/davay/android/feature/coincidences/presentation/CoincidencesViewModel.kt
> +            val hasNetworkAccess = checkNetworkState(connectivityManager)
Можно. Забыл про наличие контекста в Dagger'е. Вынесу туда.

2024-06-12 14:23 UTC, Megrief commented on app/src/main/java/com/davay/android/feature/coincidences/presentation/CoincidencesViewModel.kt
> +            val hasNetworkAccess = checkNetworkState(connectivityManager)
На него не указывала ссылка из таски. Сделаю следующим pr'ом.

2024-06-16 07:14 UTC, DimaK21 commented
Тут уже есть немного и data, и domain слой. Нужно обсудить на созвоне, как будем их делать, чтоб у всех одинаково было.
Плюс типы ошибок в состоянии экрана вроде хотели делать общие для всех экранов, так как в фигме всего 3 варианта для отображения.
А в ПР вроде всё ок 👌

2024-06-18 20:47 UTC, Secur1ty-21 approved these changes

2024-06-18 20:52 UTC, merged